{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm-sync-tracker.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ .Values.environment }}
    release: {{ $releaseName }}
    {{- include "osm-sync-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.enableInternalDb }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  {{- if not .Values.dbConfig.sslAuth.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  {{- end }}
  {{- else }}
  DB_USERNAME: {{ .Values.dbConfig.username | b64enc }}
  {{- if not .Values.dbConfig.sslAuth.enabled }}
  DB_PASSWORD: {{ .Values.dbConfig.password | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
