{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm-sync-tracker.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "osm-sync-tracker.environment" . }}
    release: {{ $releaseName }}
    {{- include "osm-sync-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.dbConfig.username | b64enc }}
  DB_PASSWORD: {{ .Values.dbConfig.password | b64enc }}
{{- if or (ne .Values.redis.username "") (ne .Values.redis.password "") }}
  REDIS_USERNAME: {{ .Values.redis.username | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
{{- end }}
{{- end }}
