{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm-sync-tracker.name" . -}}
{{- $cloudProviderName := .Values.cloudProvider.name -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ .Values.environment }}
    release: {{ $releaseName }}
    {{- include "osm-sync-tracker.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderName "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "osm-sync-tracker.selectorLabels" . | nindent 4 }}
{{- end }}
