# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
replicaCount: 1
enabled: true
initialDelaySeconds: 600
environment: development
nodeSelector: {}
tolerations: []
affinity: {}
cloudProvider:
  flavor: openshift
  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
image:
  repository: osm-sync-tracker
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.2.5-rc3"
resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  requestPayloadLimit: 1mb
  responseCompressionEnabled: true
  tracing:
    enabled: false
    url: 'http://localhost:55681/v1/trace'
  metrics:
    enabled: false
    url: 'http://localhost:55681/v1/metrics'


appConfig:
  transactionRetryPolicy:
    enabled: true
    amount: 10

# external
dbConfig:
  host: 10.8.1.4
  username: vector
  #password: postgres
  database: osm-sync-tracker-dev
  sslAuth:
    enabled: true
    secretName: cert-cluster-secret
    certFileName: postgresql.crt
    keyFileName: postgresql.key
    caFileName: root.crt
route:
  enabled: true
  path: /