# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

annotations: {}
podAnnotations: {}

replicaCount: 1
enabled: true
initialDelaySeconds: 600
environment: development
nodeSelector: {}
tolerations: []
affinity: {}

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: my-registry.io

image:
  repository: osm-sync-tracker
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "v1.0.0"
  pullPolicy: Always

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  requestPayloadLimit: 1mb
  responseCompressionEnabled: true
  tracing:
    enabled: false
    url: 'http://localhost:55681/v1/trace'
    ratio: 1
  metrics:
    enabled: false
    url: 'http://localhost:55681/v1/metrics'

# external
dbConfig:
  host: localhost
  username: postgres
  password: postgres
  database: osm-sync-tracker
  # port: 5432
  sslAuth:
    enabled: false
    secretName: secret-name
    certFileName: postgresql.crt
    keyFileName: postgresql.key
    caFileName: root.crt

redis:
  host: localhost
  username: ""
  password: ""
  db: 0
  port: 6379
  sslAuth:
    enabled: false
    secretName: secret-name
    certFileName: postgresql.crt
    keyFileName: postgresql.key
    caFileName: root.crt

closure:
  uiPath: /closure
  queues:
    changesets:
      queueOptions:
        enabledBatchJobs: true
        maxBatchSize: 10
      jobOptions:
        attempts: 10
        delay: 60000
        deduplicationDelay: 60000
        backoff:
          type: fixed
          delay: 60000
      workerOptions:
        concurrency: 1
        limiter:
          enabled: false
          # max: 10
          # duration: 1000
        maxStalledCount: 1
        stalledInterval: 30000
        removeOnComplete:
          age: 604800
          # count: 100000
        removeOnFail:
          age: 2419200
          # count: 100000
        transactionIsolationLevel: 'SERIALIZABLE'
        transactionFailureDelay: 10000
    files:
      queueOptions:
        enabledBatchJobs: false
        # maxBatchSize: 100
      jobOptions:
        attempts: 10
        delay: 60000
        deduplicationDelay: 60000
        backoff:
          type: fixed
          delay: 60000
      workerOptions:
        concurrency: 1
        limiter:
          enabled: false
          # max: 10
          # duration: 1000
        maxStalledCount: 1
        stalledInterval: 30000
        removeOnComplete:
          age: 604800
          # count: 100000
        removeOnFail:
          age: 2419200
          # count: 100000
        transactionIsolationLevel: 'SERIALIZABLE'
        transactionFailureDelay: 10000
    syncs:
      queueOptions:
        enabledBatchJobs: false
        # maxBatchSize: 100
      jobOptions:
        attempts: 10
        delay: 60000
        deduplicationDelay: 60000
        backoff:
          type: fixed
          delay: 60000
      workerOptions:
        concurrency: 1
        limiter:
          enabled: false
          # max: 10
          # duration: 1000
        maxStalledCount: 1
        stalledInterval: 30000
        removeOnComplete:
          age: 604800
          # count: 100000
        removeOnFail:
          age: 2419200
          # count: 100000
        transactionIsolationLevel: 'SERIALIZABLE'
        transactionFailureDelay: 10000

route:
  enabled: true
  path: /
  tls:
    termination: edge
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)
