name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/Libot-Mipui-Org/osm-sync-tracker
            azure-pipeline-name: 'build-and-push-to-ACR'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for CHANGELOG.md
        uses: actions/checkout@v2

      - name: Publish Release to Github
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build_and_push:
    runs-on: ubuntu-latest
    env:
      Docker_Repository: ${{ secrets.ACR_URL }}/${{ github.event.repository.name }}:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_PUSH_USER }}
          password: ${{ secrets.ACR_PUSH_TOKEN }}
      - name: downcase repository
        run: |
          echo "Docker_Repository=${Docker_Repository,,}" >>${GITHUB_ENV}
      - run: docker build . -t ${{ env.Docker_Repository }}
      - run: docker push ${{ env.Docker_Repository }}
